baseURL = "http://kyb3rfett.me"
title = "Kyb3r Fett"

# language
languageCode = "en-us"
defaultContentLanguage = "en"

# theme
theme = "LoveIt"
# emojis enable
enableEmoji = true
[params.page]
# font awesome enable
fontawesome = true

[params]
  # LoveIt theme version
  version = "0.2.X"
  # site description
  description = "Kyb3r Fett Blog and Website"
  # site keywords
  keywords = ["Kyb3r", "Kyb3r Fett", "Hacker"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # others
  gitRepo = "https://github.com/kyb3rfett/kyb3rfett.me"
  dateFormat = "2006-01-02"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

[params.app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "Kyb3r Fett"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Android browser theme color
  themeColor = "#ffffff"
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"

# search config
[params.search]
  enable = false
  type = "algolia"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 30
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = "index.en"
    appID = "PASDMWALPK"
    searchKey = "b42948e51daaa93df92381c8e2ac0f93"

# Header config
[params.header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"

# Footer config
[params.footer]
  enable = true
  # Gohugo info
  hugo = false
  # copyright infomation
  copyright = true
  # author information
  author = true
  # site creation time
  since = 2021
  license = '<a rel="license external nofollow noopener noreffer" href="https://github.com/kyb3rfett/kyb3rfett.me/blob/main/LICENSE" target="_blank">License & Copyright</a>'

  # section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      # Gravatar Profile Photo Email
      gravatarEmail = "me@kyb3rfett.me"
      title = "Kyb3r Fett"
      subtitle = "💻 Programmer/SysAdmin/Hacker? | 📖 He/him"
      typeit = true
      social = true
      disclaimer = "Don't forget to check:"
    # Home page posts
    [params.home.posts]
      enable = true
      # posts in home
      paginate = 6
      defaultHiddenFromHomePage = false

[params.social]
  GitHub = "kyb3rfett"
  Twitter = "kyb3rfett"
  Instagram = "kyb3rfett"
  Keybase = "kyb3rfett"
  Telegram = "kyb3rfett"
  Reddit = "kyb3rfett"
  GitLab = "kyb3rfett"
  mastodon = "@kyb3rfett"
  matrix = "@kyb3rfett:matrix.org"
  Snapchat = "kyb3rfett"
  Youtubechannel = "UCdowX_8Ue6b_Sfkx4bX_Gfg"
  Twitch = "kyb3rfett"
  Spotify = "3e7zcx4j0yv93iqbv78v4i6kq"
  Email = "contact@kyb3rfett.me"
  RSS = true

[params.page.share]
  enable = true
  Twitter = true
  Facebook = true
  Whatsapp = true
  HackerNews = true
  Reddit = true

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false